"""
Installer Configuration
Configuration for Inno Setup installer.
"""

import os
import sys
from pathlib import Path

# Основные настройки
APP_NAME = "Qwen Medical Transcriber"
APP_VERSION = "2.0.0"
APP_PUBLISHER = "Qwen Medical Team"
APP_URL = "https://github.com/qwen-medical/transcriber"

# Директории
BASE_DIR = Path(__file__).parent.parent
BUILD_DIR = BASE_DIR / "win32" / "build"
OUTPUT_DIR = BASE_DIR / "dist"
APP_DIR = BASE_DIR / "app"
MODELS_DIR = BASE_DIR / "models"

# Файлы приложения
APP_FILES = [
    "app/__init__.py",
    "app/main.py",
    "app/processor.py",
    "app/audio_converter.py",
    "app/asr.py",
    "app/diarization.py",
    "app/aligner.py",
    "app/docx_generator.py",
    "app/utils.py",
    "win32/gui/__init__.py",
    "win32/gui/main_window.py",
    "win32/gui/settings_window.py",
    "win32/gui/progress_dialog.py",
    "win32/gui/styles.py",
]

# Включаемые файлы
INCLUDE_FILES = [
    # Python DLL
    "python311.dll",
    # Библиотеки
    "PyQt5",  # Для gradio
    "customtkinter",
    "tkinter",
    # Модели (опционально - см. ниже)
]

# Исключения (не включать в инсталлятор)
EXCLUDE_FILES = [
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".git",
    ".gitignore",
    "*.log",
    "*.tmp",
    "*.md",
    ".env",
    "venv",
    "ENV",
    "__pycache__",
]

# Зависимости
DEPENDENCIES = [
    "torch",
    "transformers",
    "qwen-asr",
    "pyannote.audio",
    "python-docx",
    "gradio",
    "soundfile",
    "librosa",
    "customtkinter",
    "Pillow",
    "loguru",
]

# Файлы для включения в установку моделей (опционально)
OPTIONAL_MODELS = [
    ("Qwen3-ASR-1.7B", "Модель транскрипции Qwen3-ASR-1.7B"),
    ("Qwen3-ForcedAligner-0.6B", "Модель выравнивания Qwen3-ForcedAligner-0.6B"),
    ("pyannote-speaker-diarization-3.1", "Модель диаризации pyannote 3.1"),
]


def get_model_path(model_name: str) -> str:
    """Получить путь к модели."""
    return str(MODELS_DIR / model_name)


def get_size(path: Path) -> int:
    """Получить размер файла или папки в байтах."""
    if path.is_file():
        return path.stat().st_size
    elif path.is_dir():
        total = 0
        for child in path.rglob("*"):
            if child.is_file():
                total += child.stat().st_size
        return total
    return 0


def get_files_to_include():
    """Получить список файлов для включения в установку."""
    files = []

    for pattern in APP_FILES:
        path = BASE_DIR / pattern
        if path.exists():
            files.append(str(path))

    # Добавить модули Python
    import site
    site_packages = site.getsitepackages()
    for sp in site_packages:
        sp_path = Path(sp)
        for dep in DEPENDENCIES:
            dep_path = sp_path / dep.replace("-", "_")
            if dep_path.exists():
                files.append(str(dep_path))
                break

    return files


def generate_inno_setup_script() -> str:
    """Сгенерировать скрипт Inno Setup."""
    script = f"""; Inno Setup Script for {APP_NAME}
; Auto-generated by installer_config.py

#define AppName "{APP_NAME}"
#define AppVersion "{APP_VERSION}"
#define AppPublisher "{APP_PUBLISHER}"
#define AppURL "{APP_URL}"
#define InstallDir "{str(BASE_DIR).replace(chr(92), chr(92)+chr(92))}"

[Setup]
; Settings
AppName={APP_NAME}
AppVersion={APP_VERSION}
AppPublisher={APP_PUBLISHER}
AppPublisherURL={APP_URL}
AppSupportURL={APP_URL}/issues
AppUpdatesURL={APP_URL}/releases
DefaultDirName={{pf}}\\{APP_NAME}
DefaultGroupName={APP_NAME}
AllowNoIcons=yes
LicenseFile=
SetupIconFile=resources/icon.ico
UninstallDisplayIcon={{app}}\\QwenTranscriber.exe
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
 ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

; File associations
ChangesAssociations=yes
FileAssociation=ext:.wav type:"Qwen Audio" cmd:""{{app}}\\QwenTranscriber.exe" "%1"
"""

    # Directory definitions
    script += """
[Directories]
; Создание папки для моделей
Name: "{app}\\models"; Flags: uninsalwaysuninstall
"""

    # File definitions
    script += """
[Files]
; Основные файлы приложения
"""

    # Получить файлы
    files_to_include = get_files_to_include()
    for file in files_to_include:
        source = file.replace(chr(92), chr(92)+chr(92))
        dest = source.replace(chr(92).replace(str(BASE_DIR).replace(chr(92), chr(92)), "{app}")
        script += f'Source: "{source}"; DestDir: "{{app}}\\{os.path.dirname(dest)}"; Flags: ignoreversion\n'

    # Модели (опционально)
    script += """
; Модели (опционально - см. задачу установки моделей)
; Раскомментируйте и измените пути при наличии локальных моделей
; Source: "{#InstallDir}\\models\\Qwen3-ASR-1.7B\\*"; DestDir: "{{app}}\\models\\Qwen3-ASR-1.7B"; Flags: ignoreversion recursesubdirs createallsubdirs
; Source: "{#InstallDir}\\models\\Qwen3-ForcedAligner-0.6B\\*"; DestDir: "{{app}}\\models\\Qwen3-ForcedAligner-0.6B"; Flags: ignoreversion recursesubdirs createallsubdirs
; Source: "{#InstallDir}\\models\\pyannote-speaker-diarization-3.1\\*"; DestDir: "{{app}}\\models\\pyannote-speaker-diarization-3.1"; Flags: ignoreversion recursesubdirs createallsubdirs
"""

    # Registry
    script += """
[Registry]
; Зарегистрировать в системе
Root: HKLM; Subkey: "SOFTWARE\\{APP_NAME}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\\{APP_NAME}"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"
Root: HKLM; Subkey: "SOFTWARE\\{APP_NAME}"; ValueType: string; ValueName: "Version"; ValueData: "{#APP_VERSION}"

; Ассоциация файлов
Root: HKCR; Subkey: ".wav"; ValueType: string; ValueName: ""; ValueData: "QwenAudioFile"; Flags: uninsdeletekey
Root: HKCR; Subkey: "QwenAudioFile"; ValueType: string; ValueName: ""; ValueData: "Qwen Audio File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "QwenAudioFile\\shell\\open\\command"; ValueType: string; ValueName: ""; ValueData: """ + '"\\"{app}\\QwenTranscriber.exe\\" \\"%1\\""'
"""

    # Run
    script += """
[Run]
; Запуск пост-установки
Filename: "{{app}}\\post_install.exe"; Flags: runhidden
"""

    # Icons
    script += """
[Icons]
Name: "{group}\\{#AppName}"; Filename: "{app}\\QwenTranscriber.exe"
Name: "{group}\\{#AppName} (Настройки)"; Filename: "{app}\\QwenTranscriber.exe"; Parameters: "--settings"
Name: "{group}\\Удалить {#AppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\\{#AppName}"; Filename: "{app}\\QwenTranscriber.exe"
"""

    # Code
    script += """
[Code]
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    Exec(ExpandConstant('{app}\\post_install.exe'), '', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;
"""

    return script


if __name__ == "__main__":
    # Генерация скрипта
    script = generate_inno_setup_script()
    output_file = BASE_DIR / "win32" / "installer" / "setup.iss"
    output_file.write_text(script, encoding="utf-8")
    print(f"Скрипт Inno Setup сгенерирован: {output_file}")

    # Информация о размерах
    print("\n=== Размеры ===")
    print(f"Базовая директория: {BASE_DIR}")
    if MODELS_DIR.exists():
        for model in OPTIONAL_MODELS:
            model_path = get_model_path(model[0])
            if Path(model_path).exists():
                size = get_size(Path(model_path))
                print(f"{model[0]}: {size / (1024*1024):.2f} MB")
